# Generated by Django 3.0.8 on 2020-07-30 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_system', '0002_auto_20200730_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErpEmployees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('emp_middle_name', models.CharField(max_length=25, verbose_name='Отчество')),
                ('emp_second_name', models.CharField(db_index=True, max_length=25, verbose_name='Фамилия')),
                ('emp_phone', models.CharField(max_length=11)),
                ('emp_dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='erp_system.ErpJobDepartment', verbose_name='Отдел')),
                ('emp_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='erp_system.ErpJobName', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
