# Generated by Django 3.0.8 on 2020-07-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_system', '0003_erpemployees'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErpJobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=20, verbose_name='Тип задания')),
            ],
            options={
                'verbose_name': 'Тип задания',
            },
        ),
        migrations.CreateModel(
            name='ErpJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_addr', models.CharField(max_length=100, verbose_name='Адрес')),
                ('pr_type', models.CharField(choices=[('pr', 'ПР'), ('nrd', 'НРД'), ('rtk', 'РТК')], max_length=3)),
                ('job_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='erp_system.ErpJobType', verbose_name='Тип объекта')),
            ],
        ),
    ]
