# Generated by Django 3.0.8 on 2020-07-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_system', '0004_erpjob_erpjobtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='erpjob',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelOptions(
            name='erpjobtype',
            options={'verbose_name': 'Тип задания', 'verbose_name_plural': 'Типы заданий'},
        ),
        migrations.AlterField(
            model_name='erpjob',
            name='pr_type',
            field=models.CharField(choices=[(None, 'Выберите тип'), ('1', 'ПР'), ('2', 'НРД'), ('3', 'РТК')], default=None, max_length=5, verbose_name='Тип задания'),
        ),
    ]
