# Generated by Django 3.0.8 on 2020-07-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_system', '0005_auto_20200730_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpjob',
            name='pr_number',
            field=models.PositiveSmallIntegerField(default=1, max_length=6, verbose_name='Номер задания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='erpjob',
            name='Дата создания',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='erpjob',
            name='pr_type',
            field=models.CharField(choices=[(None, 'Выберите тип'), ('ПР', 'ПР'), ('НРД', 'НРД'), ('РТК', 'РТК')], default='НРД', max_length=5, verbose_name='Тип задания'),
        ),
    ]
