# Generated by Django 3.0.8 on 2020-08-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_system', '0006_auto_20200730_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpjob',
            name='pr_number',
            field=models.PositiveSmallIntegerField(verbose_name='Номер задания'),
        ),
    ]
